In [2]:
! pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.25.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: scipy>=1.16.3 in /opt/anaconda3/lib/python3.13/site-packages (from mlxtend) (1.16.3)
Requirement already satisfied: numpy>=2.3.5 in /opt/anaconda3/lib/python3.13/site-packages (from mlxtend) (2.3.5)
Requirement already satisfied: pandas>=2.3.3 in /opt/anaconda3/lib/python3.13/site-packages (from mlxtend) (2.3.3)
Collecting scikit-learn>=1.8.0 (from mlxtend)
  Downloading scikit_learn-1.9.0-cp313-cp313-macosx_12_0_arm64.whl.metadata (11 kB)
Collecting matplotlib>=3.10.8 (from mlxtend)
  Downloading matplotlib-3.11.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (80 kB)
Requirement already satisfied: joblib>=1.5.2 in /opt/anaconda3/lib/python3.13/site-packages (from mlxtend) (1.5.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (25.0)
Requirement already satisfied: pillow>=9 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: narwhals>=2.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn>=1.8.0->mlxtend) (2.7.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn>=1.8.0->mlxtend) (3.5.0)
Downloading mlxtend-0.25.0-py3-none-any.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 3.5 MB/s  0:00:00m 4.7 MB/s eta 0:00:01
Downloading matplotlib-3.11.0-cp313-cp313-macosx_11_0_arm64.whl (9.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.3/9.3 MB 3.9 MB/s  0:00:023.9 MB/s eta 0:00:01:01
Downloading scikit_learn-1.9.0-cp313-cp313-macosx_12_0_arm64.whl (8.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 3.8 MB/s  0:00:023.9 MB/s eta 0:00:01:01
Installing collected packages: scikit-learn, matplotlib, mlxtend
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.7.2
    Uninstalling scikit-learn-1.7.2:
      Successfully uninstalled scikit-learn-1.7.2
  Attempting uninstall: matplotlib━━━━━━━━━━━━━━━━━━━━ 0/3 [scikit-learn]
    Found existing installation: matplotlib 3.10.0 0/3 [scikit-learn]
    Uninstalling matplotlib-3.10.0:━━━━━━━━━━━━━━━ 0/3 [scikit-learn]
      Successfully uninstalled matplotlib-3.10.0m╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/3 [matplotlib]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [mlxtend]━━━ 1/3 [matplotlib]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ydata-profiling 4.18.4 requires matplotlib<=3.10,>=3.5, but you have matplotlib 3.11.0 which is incompatible.
Successfully installed matplotlib-3.11.0 mlxtend-0.25.0 scikit-learn-1.9.0

In [3]:
conda install -c conda-forge mlxtend

Jupyter detected...
2 channel Terms of Service accepted
Retrieving notices: done
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
    current version: 26.1.1
    latest version: 26.5.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /opt/anaconda3

  added / updated specs:
    - mlxtend


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2026.6.17  |       hbd8a1cb_0         126 KB  conda-forge
    certifi-2026.6.17          |     pyhd8ed1ab_0         131 KB  conda-forge
    libfreetype-2.13.3         |       hce30654_1           8 KB  conda-forge
    libfreetype6-2.13.3        |       h1d14073_1         326 KB  conda-forge
    matplotlib-base-3.10.6     |  py313h58042b9_1         7.9 MB  conda-forge
    mlxtend-0.25.0             |     pyhd8ed1ab_0         1.2 MB  conda-forge
    openssl-3.6.3              |       hd24854e_0         3.0 MB  conda-forge
    qhull-2020.2               |       h420ef59_5         504 KB  conda-forge
    scikit-learn-1.9.0         |np2py313h3b23316_0         9.1 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        22.3 MB

The following NEW packages will be INSTALLED:

  libfreetype        conda-forge/osx-arm64::libfreetype-2.13.3-hce30654_1
  libfreetype6       conda-forge/osx-arm64::libfreetype6-2.13.3-h1d14073_1
  matplotlib-base    conda-forge/osx-arm64::matplotlib-base-3.10.6-py313h58042b9_1
  mlxtend            conda-forge/noarch::mlxtend-0.25.0-pyhd8ed1ab_0
  qhull              conda-forge/osx-arm64::qhull-2020.2-h420ef59_5
  scikit-learn       conda-forge/osx-arm64::scikit-learn-1.9.0-np2py313h3b23316_0

The following packages will be UPDATED:

  ca-certificates    pkgs/main/osx-arm64::ca-certificates-~ --> conda-forge/noarch::ca-certificates-2026.6.17-hbd8a1cb_0
  certifi            pkgs/main/osx-arm64::certifi-2026.5.2~ --> conda-forge/noarch::certifi-2026.6.17-pyhd8ed1ab_0
  openssl               pkgs/main::openssl-3.5.6-ha0b305a_0 --> conda-forge::openssl-3.6.3-hd24854e_0



Downloading and Extracting Packages:
scikit-learn-1.9.0   | 9.1 MB    |                                       |   0%
matplotlib-base-3.10 | 7.9 MB    |                                       |   0%

openssl-3.6.3        | 3.0 MB    |                                       |   0%


mlxtend-0.25.0       | 1.2 MB    |                                       |   0%



qhull-2020.2         | 504 KB    |                                       |   0%




libfreetype6-2.13.3  | 326 KB    |                                       |   0%





certifi-2026.6.17    | 131 KB    |                                       |   0%






ca-certificates-2026 | 126 KB    |                                       |   0%







libfreetype-2.13.3   | 8 KB      |                                       |   0%



qhull-2020.2         | 504 KB    | #1                                    |   3%

openssl-3.6.3        | 3.0 MB    | 1                                     |   1%


mlxtend-0.25.0       | 1.2 MB    | 4                                     |   1%



qhull-2020.2         | 504 KB    | ##################7                   |  51%

openssl-3.6.3        | 3.0 MB    | ###3                                  |   9%


mlxtend-0.25.0       | 1.2 MB    | ########5                             |  23%


mlxtend-0.25.0       | 1.2 MB    | #############8                        |  37%

openssl-3.6.3        | 3.0 MB    | #####                                 |  14%


scikit-learn-1.9.0   | 9.1 MB    |                                       |   0%



qhull-2020.2         | 504 KB    | #############################3        |  79%
matplotlib-base-3.10 | 7.9 MB    |                                       |   0%

openssl-3.6.3        | 3.0 MB    | ######4                               |  17%



qhull-2020.2         | 504 KB    | ##################################### | 100%


scikit-learn-1.9.0   | 9.1 MB    | 6                                     |   2%



qhull-2020.2         | 504 KB    | ##################################### | 100%



qhull-2020.2         | 504 KB    | ##################################### | 100%

openssl-3.6.3        | 3.0 MB    | #########7                            |  26%


mlxtend-0.25.0       | 1.2 MB    | ##################################### | 100%
matplotlib-base-3.10 | 7.9 MB    | 8                                     |   2%


mlxtend-0.25.0       | 1.2 MB    | ##################################### | 100%





certifi-2026.6.17    | 131 KB    | ####5                                 |  12%

openssl-3.6.3        | 3.0 MB    | ###########7                          |  32%





certifi-2026.6.17    | 131 KB    | ####################################2 |  98%





certifi-2026.6.17    | 131 KB    | ##################################### | 100%




libfreetype6-2.13.3  | 326 KB    | #8                                    |   5%





certifi-2026.6.17    | 131 KB    | ##################################### | 100%




scikit-learn-1.9.0   | 9.1 MB    | 9                                     |   3%

openssl-3.6.3        | 3.0 MB    | #############4                        |  36%
matplotlib-base-3.10 | 7.9 MB    | #3                                    |   4%






ca-certificates-2026 | 126 KB    | ####7                                 |  13%




libfreetype6-2.13.3  | 326 KB    | ##################################### | 100%

scikit-learn-1.9.0   | 9.1 MB    | #5                                    |   4%




libfreetype6-2.13.3  | 326 KB    | ##################################### | 100%




libfreetype6-2.13.3  | 326 KB    | ##################################### | 100%






ca-certificates-2026 | 126 KB    | ##################################### | 100%
matplotlib-base-3.10 | 7.9 MB    | ##1                                   |   6%






ca-certificates-2026 | 126 KB    | ##################################### | 100%

scikit-learn-1.9.0   | 9.1 MB    | #8                                    |   5%







libfreetype-2.13.3   | 8 KB      | ##################################### | 100%







libfreetype-2.13.3   | 8 KB      | ##################################### | 100%







libfreetype-2.13.3   | 8 KB      | ##################################### | 100%
scikit-learn-1.9.0   | 9.1 MB    | ##2                                   |   6%

openssl-3.6.3        | 3.0 MB    | #########################7            |  70%
matplotlib-base-3.10 | 7.9 MB    | ###3                                  |   9%

scikit-learn-1.9.0   | 9.1 MB    | ##8                                   |   8%
matplotlib-base-3.10 | 7.9 MB    | ###9                                  |  11%

scikit-learn-1.9.0   | 9.1 MB    | ###2                                  |   9%
matplotlib-base-3.10 | 7.9 MB    | ####4                                 |  12%

scikit-learn-1.9.0   | 9.1 MB    | ###6                                  |  10%
scikit-learn-1.9.0   | 9.1 MB    | ###9                                  |  11%
scikit-learn-1.9.0   | 9.1 MB    | ####6                                 |  12%
matplotlib-base-3.10 | 7.9 MB    | ######3                               |  17%
scikit-learn-1.9.0   | 9.1 MB    | #####1                                |  14%
scikit-learn-1.9.0   | 9.1 MB    | #####6                                |  15%
scikit-learn-1.9.0   | 9.1 MB    | ######8                               |  18%
scikit-learn-1.9.0   | 9.1 MB    | #######7                              |  21%
scikit-learn-1.9.0   | 9.1 MB    | ########5                             |  23%
scikit-learn-1.9.0   | 9.1 MB    | #########7                            |  26%
scikit-learn-1.9.0   | 9.1 MB    | ##########7                           |  29%
scikit-learn-1.9.0   | 9.1 MB    | ###########6                          |  31%
scikit-learn-1.9.0   | 9.1 MB    | ############5                         |  34%
scikit-learn-1.9.0   | 9.1 MB    | ##############3                       |  39%
scikit-learn-1.9.0   | 9.1 MB    | #################                     |  46%
scikit-learn-1.9.0   | 9.1 MB    | ##################2                   |  49%
matplotlib-base-3.10 | 7.9 MB    | #####################8                |  59%
scikit-learn-1.9.0   | 9.1 MB    | ####################8                 |  56%
scikit-learn-1.9.0   | 9.1 MB    | ######################                |  60%
scikit-learn-1.9.0   | 9.1 MB    | #######################1              |  62%
scikit-learn-1.9.0   | 9.1 MB    | ########################1             |  65%
scikit-learn-1.9.0   | 9.1 MB    | #########################2            |  68%
scikit-learn-1.9.0   | 9.1 MB    | ##########################2           |  71%
scikit-learn-1.9.0   | 9.1 MB    | ###########################1          |  73%
scikit-learn-1.9.0   | 9.1 MB    | ############################          |  76%
scikit-learn-1.9.0   | 9.1 MB    | #############################6        |  80%
matplotlib-base-3.10 | 7.9 MB    | ################################      |  87%
scikit-learn-1.9.0   | 9.1 MB    | ###############################5      |  85%
matplotlib-base-3.10 | 7.9 MB    | #################################7    |  91%
scikit-learn-1.9.0   | 9.1 MB    | ################################5     |  88%
scikit-learn-1.9.0   | 9.1 MB    | ##################################    |  92%
scikit-learn-1.9.0   | 9.1 MB    | ###################################   |  95%
scikit-learn-1.9.0   | 9.1 MB    | ##################################### | 100%





































Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Channel "defaults" has the following notices:
  [info] -- Tue Jun  9 00:00:00 2026
  PyTorch 2.12 with CUDA support is now available to install with your current channel (Anaconda Main). Learn more: https://anaconda.org/main/pytorch?utm_source=channel_notices


Note: you may need to restart the kernel to use updated packages.

In [1]:
# importing the libraries
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori,association_rules

In [3]:
titanic = pd.read_csv('/Users/furkhanansari/Desktop/Data Science/DataSets/Titanic.csv')
titanic.head()

  Class Gender    Age Survived
0   3rd   Male  Child       No
1   3rd   Male  Child       No
2   3rd   Male  Child       No
3   3rd   Male  Child       No
4   3rd   Male  Child       No

In [5]:
df = pd.get_dummies(titanic)
df

,Class_1st,Class_2nd,Class_3rd,Class_Crew,Gender_Female,Gender_Male,Age_Adult,Age_Child,Survived_No,Survived_Yes
0,False,False,True,False,False,True,False,True,True,False
1,False,False,True,False,False,True,False,True,True,False
2,False,False,True,False,False,True,False,True,True,False
3,False,False,True,False,False,True,False,True,True,False
4,False,False,True,False,False,True,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...
2196,False,False,False,True,True,False,True,False,False,True
2197,False,False,False,True,True,False,True,False,False,True
2198,False,False,False,True,True,False,True,False,False,True
2199,False,False,False,True,True,False,True,False,False,True
2200,False,False,False,True,True,False,True,False,False,True

In [7]:
# Apriori Algorithm

In [13]:
frequent_itemset = apriori(df,min_support=0.1 , use_colnames=True)
frequent_itemset

     support                                           itemsets
0   0.147660                                        (Class_1st)
1   0.129487                                        (Class_2nd)
2   0.320763                                        (Class_3rd)
3   0.402090                                       (Class_Crew)
4   0.213539                                    (Gender_Female)
5   0.786461                                      (Gender_Male)
6   0.950477                                        (Age_Adult)
7   0.676965                                      (Survived_No)
8   0.323035                                     (Survived_Yes)
9   0.144934                             (Class_1st, Age_Adult)
10  0.118582                             (Class_2nd, Age_Adult)
11  0.231713                           (Class_3rd, Gender_Male)
12  0.284871                             (Class_3rd, Age_Adult)
13  0.239891                           (Class_3rd, Survived_No)
14  0.391640                          (Gender_Male, Class_Crew)
15  0.402090                            (Age_Adult, Class_Crew)
16  0.305770                          (Class_Crew, Survived_No)
17  0.193094                         (Age_Adult, Gender_Female)
18  0.156293                      (Gender_Female, Survived_Yes)
19  0.757383                           (Age_Adult, Gender_Male)
20  0.619718                         (Gender_Male, Survived_No)
21  0.166742                        (Survived_Yes, Gender_Male)
22  0.653339                           (Age_Adult, Survived_No)
23  0.297138                          (Age_Adult, Survived_Yes)
24  0.209905                (Class_3rd, Age_Adult, Gender_Male)
25  0.191731              (Class_3rd, Gender_Male, Survived_No)
26  0.216265                (Class_3rd, Age_Adult, Survived_No)
27  0.391640               (Age_Adult, Gender_Male, Class_Crew)
28  0.304407             (Class_Crew, Gender_Male, Survived_No)
29  0.305770               (Age_Adult, Class_Crew, Survived_No)
30  0.143571           (Age_Adult, Gender_Female, Survived_Yes)
31  0.603816              (Age_Adult, Gender_Male, Survived_No)
32  0.153567             (Age_Adult, Survived_Yes, Gender_Male)
33  0.175829   (Age_Adult, Class_3rd, Gender_Male, Survived_No)
34  0.304407  (Age_Adult, Class_Crew, Gender_Male, Survived_No)

In [16]:
rules = association_rules(frequent_itemset , metric = 'lift' , min_threshold =0.7)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Class_1st),(Age_Adult),0.147660,0.950477,0.144934,0.981538,1.032680,1.0,0.004587,2.682493,0.037128,0.152050,0.627212,0.567012
1,(Age_Adult),(Class_1st),0.950477,0.147660,0.144934,0.152486,1.032680,1.0,0.004587,1.005694,0.639010,0.152050,0.005661,0.567012
2,(Class_2nd),(Age_Adult),0.129487,0.950477,0.118582,0.915789,0.963505,1.0,-0.004492,0.588085,-0.041697,0.123346,-0.700435,0.520275
3,(Age_Adult),(Class_2nd),0.950477,0.129487,0.118582,0.124761,0.963505,1.0,-0.004492,0.994601,-0.433377,0.123346,-0.005429,0.520275
4,(Class_3rd),(Gender_Male),0.320763,0.786461,0.231713,0.722380,0.918520,1.0,-0.020555,0.769177,-0.115514,0.264660,-0.300090,0.508503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,"(Class_Crew, Gender_Male)","(Age_Adult, Survived_No)",0.391640,0.653339,0.304407,0.777262,1.189676,1.0,0.048533,1.556362,0.262074,0.411043,0.357476,0.621594
102,(Survived_No),"(Age_Adult, Class_Crew, Gender_Male)",0.676965,0.391640,0.304407,0.449664,1.148157,1.0,0.039280,1.105434,0.399458,0.398335,0.095378,0.613463
103,(Age_Adult),"(Class_Crew, Gender_Male, Survived_No)",0.950477,0.304407,0.304407,0.320268,1.052103,1.0,0.015075,1.023334,1.000000,0.320268,0.022802,0.660134
104,(Gender_Male),"(Age_Adult, Class_Crew, Survived_No)",0.786461,0.305770,0.304407,0.387060,1.265851,1.0,0.063931,1.132622,0.983509,0.386390,0.117093,0.691301
105,(Class_Crew),"(Age_Adult, Gender_Male, Survived_No)",0.402090,0.603816,0.304407,0.757062,1.253795,1.0,0.061619,1.630802,0.338549,0.433938,0.386805,0.630600

In [19]:
# sorting top 20 rules based on height lift vlaues
rules.sort_values('lift' , ascending = False)[0:20]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
65,"(Age_Adult, Gender_Female)",(Survived_Yes),0.193094,0.323035,0.143571,0.743529,2.301699,1.0,0.081195,2.639542,0.700873,0.385366,0.621146,0.593987
68,(Survived_Yes),"(Age_Adult, Gender_Female)",0.323035,0.193094,0.143571,0.444444,2.301699,1.0,0.081195,1.452431,0.835403,0.385366,0.311499,0.593987
18,(Survived_Yes),(Gender_Female),0.323035,0.213539,0.156293,0.483826,2.265745,1.0,0.087312,1.523634,0.825219,0.410992,0.343674,0.607870
19,(Gender_Female),(Survived_Yes),0.213539,0.323035,0.156293,0.731915,2.265745,1.0,0.087312,2.525187,0.710327,0.410992,0.603990,0.607870
69,(Gender_Female),"(Age_Adult, Survived_Yes)",0.213539,0.297138,0.143571,0.672340,2.262724,1.0,0.080121,2.145099,0.709577,0.391089,0.533821,0.577760
64,"(Age_Adult, Survived_Yes)",(Gender_Female),0.297138,0.213539,0.143571,0.483180,2.262724,1.0,0.080121,1.521732,0.793974,0.391089,0.342854,0.577760
99,"(Age_Adult, Gender_Male)","(Class_Crew, Survived_No)",0.757383,0.305770,0.304407,0.401920,1.314450,1.0,0.072822,1.160764,0.986022,0.401198,0.138498,0.698731
98,"(Class_Crew, Survived_No)","(Age_Adult, Gender_Male)",0.305770,0.757383,0.304407,0.995542,1.314450,1.0,0.072822,54.427079,0.344592,0.401198,0.981627,0.698731
50,(Class_Crew),"(Age_Adult, Gender_Male)",0.402090,0.757383,0.391640,0.974011,1.286022,1.0,0.087104,9.335480,0.371976,0.510059,0.892882,0.745554
47,"(Age_Adult, Gender_Male)",(Class_Crew),0.757383,0.402090,0.391640,0.517097,1.286022,1.0,0.087104,1.238157,0.916706,0.510059,0.192348,0.745554
53,"(Class_Crew, Survived_No)",(Gender_Male),0.305770,0.786461,0.304407,0.995542,1.265851,1.0,0.063931,47.903983,0.302519,0.386390,0.979125,0.691301
104,(Gender_Male),"(Age_Adult, Class_Crew, Survived_No)",0.786461,0.305770,0.304407,0.387060,1.265851,1.0,0.063931,1.132622,0.983509,0.386390,0.117093,0.691301
93,"(Age_Adult, Class_Crew, Survived_No)",(Gender_Male),0.305770,0.786461,0.304407,0.995542,1.265851,1.0,0.063931,47.903983,0.302519,0.386390,0.979125,0.691301
56,(Gender_Male),"(Class_Crew, Survived_No)",0.786461,0.305770,0.304407,0.387060,1.265851,1.0,0.063931,1.132622,0.983509,0.386390,0.117093,0.691301
105,(Class_Crew),"(Age_Adult, Gender_Male, Survived_No)",0.402090,0.603816,0.304407,0.757062,1.253795,1.0,0.061619,1.630802,0.338549,0.433938,0.386805,0.630600
92,"(Age_Adult, Gender_Male, Survived_No)",(Class_Crew),0.603816,0.402090,0.304407,0.504138,1.253795,1.0,0.061619,1.205800,0.510929,0.433938,0.170675,0.630600
11,(Gender_Male),(Class_Crew),0.786461,0.402090,0.391640,0.497978,1.238474,1.0,0.075412,1.191004,0.901730,0.491448,0.160372,0.735995
51,(Gender_Male),"(Age_Adult, Class_Crew)",0.786461,0.402090,0.391640,0.497978,1.238474,1.0,0.075412,1.191004,0.901730,0.491448,0.160372,0.735995
46,"(Age_Adult, Class_Crew)",(Gender_Male),0.402090,0.786461,0.391640,0.974011,1.238474,1.0,0.075412,8.216621,0.322047,0.491448,0.878295,0.735995
10,(Class_Crew),(Gender_Male),0.402090,0.786461,0.391640,0.974011,1.238474,1.0,0.075412,8.216621,0.322047,0.491448,0.878295,0.735995

In [20]:
# rules which are having the lift value greater than 1
rules[rules.lift>1]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Class_1st),(Age_Adult),0.147660,0.950477,0.144934,0.981538,1.032680,1.0,0.004587,2.682493,0.037128,0.152050,0.627212,0.567012
1,(Age_Adult),(Class_1st),0.950477,0.147660,0.144934,0.152486,1.032680,1.0,0.004587,1.005694,0.639010,0.152050,0.005661,0.567012
8,(Class_3rd),(Survived_No),0.320763,0.676965,0.239891,0.747875,1.104747,1.0,0.022745,1.281251,0.139592,0.316547,0.219513,0.551119
9,(Survived_No),(Class_3rd),0.676965,0.320763,0.239891,0.354362,1.104747,1.0,0.022745,1.052040,0.293515,0.316547,0.049466,0.551119
10,(Class_Crew),(Gender_Male),0.402090,0.786461,0.391640,0.974011,1.238474,1.0,0.075412,8.216621,0.322047,0.491448,0.878295,0.735995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,"(Class_Crew, Gender_Male)","(Age_Adult, Survived_No)",0.391640,0.653339,0.304407,0.777262,1.189676,1.0,0.048533,1.556362,0.262074,0.411043,0.357476,0.621594
102,(Survived_No),"(Age_Adult, Class_Crew, Gender_Male)",0.676965,0.391640,0.304407,0.449664,1.148157,1.0,0.039280,1.105434,0.399458,0.398335,0.095378,0.613463
103,(Age_Adult),"(Class_Crew, Gender_Male, Survived_No)",0.950477,0.304407,0.304407,0.320268,1.052103,1.0,0.015075,1.023334,1.000000,0.320268,0.022802,0.660134
104,(Gender_Male),"(Age_Adult, Class_Crew, Survived_No)",0.786461,0.305770,0.304407,0.387060,1.265851,1.0,0.063931,1.132622,0.983509,0.386390,0.117093,0.691301
105,(Class_Crew),"(Age_Adult, Gender_Male, Survived_No)",0.402090,0.603816,0.304407,0.757062,1.253795,1.0,0.061619,1.630802,0.338549,0.433938,0.386805,0.630600