In [12]:
from scipy import stats
import pandas as pd
import numpy as np

In [13]:
glaxo = pd.read_csv('/Users/furkhanansari/Desktop/Data Science/DataSets/glaxo_df.csv')
glaxo.head(5)

         Date      Date.1    Close      gain
0  2010-01-05  2010-01-05  1616.80 -0.005444
1  2010-01-06  2010-01-06  1638.50  0.013422
2  2010-01-07  2010-01-07  1648.70  0.006225
3  2010-01-08  2010-01-08  1639.80 -0.005398
4  2010-01-11  2010-01-11  1629.45 -0.006312

In [14]:
beml = pd.read_csv('/Users/furkhanansari/Desktop/Data Science/DataSets/beml_df.csv')
beml.head(5)

         Date      Date.1    Close      gain
0  2010-01-05  2010-01-05  1134.60 -0.000881
1  2010-01-06  2010-01-06  1139.60  0.004407
2  2010-01-07  2010-01-07  1144.15  0.003993
3  2010-01-08  2010-01-08  1144.05 -0.000087
4  2010-01-11  2010-01-11  1137.00 -0.006162

In [20]:
# finding out the Confidence Intervals of gains on both datasets(beml,glaxo)

In [21]:
glaxo_CI = stats.norm.interval(
    0.95,
    loc = glaxo.gain.mean(),
    scale = glaxo.gain.std()
)
print("Gain at 95% confidence intervals for glaxo are : " , np.round(glaxo_CI,4))

Gain at 95% confidence intervals for glaxo are :  [-0.0258  0.0266]

In [22]:
beml_CI = stats.norm.interval(
    0.95,
    loc = beml.gain.mean(),
    scale = beml.gain.std()
)
print("Gain at 95% confidence interval for beml are : " , np.round(beml_CI , 4))

Gain at 95% confidence interval for beml are :  [-0.0515  0.0521]